# Path to your keystore file
storeFile=C:\\Users\\MA Digitals\\Desktop\\Store_app\\jolovend-key.jks

# Keystore password (the one you entered during key generation)
storePassword=JOLO@@delivery@@!123Food

# Key alias (the alias you used when generating the key, in your case it's 'upload')
keyAlias=jolovkeyalias

# Key password (the password you entered for the specific key)
keyPassword=JOLO@@delivery@@!123Food